Fix: AttributeError:  for 'Image.DEBUG'
AttributeError: module 'PIL.Image' has no attribute 'DEBUG'

DEBUG was removed in: https://github.com/python-pillow/Pillow/pull/1207